### ISSUE TITLE
Cut off long thread titles names

### ISSUE THREAD

**Issue by Eldenroot** [lairdshaw/MyBB-active-threads-plugin#10]

**Comment by lairdshaw** [comment]
As best I can tell, thread titles are limited to 120 characters due to the definition of the "subject" column of the mybb_threads table. How much shorter do you want this plugin to limit them to? Can you give an example of when it would be useful?

**Comment by Eldenroot** [comment]
Idk, custom setting to prevent "double lines" in thread list? MAybe leave it as it is...

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/74369642-fc085a00-4dd5-11ea-928b-461d35a0d313.png)
