### ISSUE TITLE
Template variables {}

### ISSUE THREAD

**Issue by Eldenroot** [lairdshaw/MyBB-active-threads-plugin#12]
Why not to use all variables in same style? I mean using {}

![image](https://user-images.githubusercontent.com/778890/74104725-d110d280-4b57-11ea-9c33-3519350aa018.png)

**Comment by Eldenroot** [comment]
OK, now I get it...

Would be much better to add templates for these "links" then hardcode them in php... right now there is no way how to customize it.

**Comment by lairdshaw** [comment]
> Why not to use all variables in same style? I mean using {}

No particular reason - the curly braces are often not necessary, in which case I sometimes omit them. But you're right - it would be better to be consistent.

> Would be much better to add templates for these "links" then hardcode them in php... right now there is no way how to customize it.

I'm working on this, however, it is going to be messy to implement full templating for the contents of the $forum_links variable.

**Comment by Eldenroot** [comment]
Hmm, well, maybe templates would be great but not necessary. There is no css selector for the link so the customization is quite difficult. It is up to you buddy :)

**Comment by lairdshaw** [comment]
Hey, you wanted it, you got it. The "forum links" templates have three elements: the links, the separators for all-but-the-last, and the last separator.

**Comment by Eldenroot** [comment]
@lairdshaw - what about these two templates?

activethreads_earliestpost_date_link
activethreads_latestpost_date_link

**Comment by lairdshaw** [comment]
What about them? Do you mean "What is their purpose?" Or something else?

**Comment by Eldenroot** [comment]
For me {} is missing for these two...

**Comment by lairdshaw** [comment]
Ah, sorry for not understanding you the first time. Right you are. Will fix momentarily.
