### ISSUE TITLE
Ascending vs descending order

### ISSUE THREAD

**Issue by Eldenroot** [lairdshaw/MyBB-active-threads-plugin#14]
I think there must be something wrong, it works right opposite that it should be, can you confirm?

**Comment by lairdshaw** [comment]
Seems to work right for me. When a link to, say, "asc" is provided, that means that currently the sorting is desc, and to change to asc you need to click the link. This is semantically consistent with the way core code does it.

Or are you experiencing something different?

**Comment by Eldenroot** [comment]
OK, sorry, my fault... you are right!
