### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by Eldenroot** [lairdshaw/MyBB-active-threads-plugin#18]
Hi, I got a report from one of my users:

MyBB SQL ErrorMyBB has experienced an internal SQL error and cannot continue.
SQL Error:1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '((p.dateline >= 1584179051 AND p.dateline <= 1585388651) AND f.fid NOT IN (11,15' at line 25Query:SELECT count(*) AS cnt FROM ( SELECT t.tid, t.subject AS thread_subject, t.dateline AS thread_dateline, uthr.uid AS thread_uid, uthr.username AS thread_username, uthr.usergroup AS thread_usergroup, t.closed AS thread_closed, t.lastpost AS thread_lastpost, t.replies AS thread_replies, t.views AS thread_views, t.icon AS thread_icon, t.poll AS thread_poll, t.prefix AS thread_prefix, f.parentlist, f.fid, f.name AS forum_name, count(p.pid) AS num_posts, MIN(p.pid) AS min_pid, MAX(p.pid) AS max_pid FROM mybb_threads t INNER JOIN mybb_posts p ON t.tid = p.tid INNER JOIN mybb_forums f ON f.fid = t.fid INNER JOIN mybb_users uthr ON uthr.uid = t.uid WHERE ((p.dateline >= 1584179051 AND p.dateline <= 1585388651) AND f.fid NOT IN (11,15,13,93,14,42,62,63,41,61,47,48,53,57,49,55,54,51,52,50,56,36,39,40,34,35,84,69,70,71,77,80,68,76,73,74,75,72)((p.dateline >= 1584179051 AND p.dateline <= 1585388651) AND f.fid NOT IN (11,15,13,93,14,42,62,63,41,61,47,48,53,57,49,55,54,51,52,50,56,36,39,40,34,35,84,69,70,71,77,80,68,76,73,74,75,72) AND ((t.fid IN(11,14,39,40) AND t.uid="1168") OR t.fid NOT IN(11,14,39,40)))) AND p.visible > 0 GROUP BY p.tid) AS mainqPlease contact the MyBB Group for technical support.

**Comment by lairdshaw** [comment]
Thank you, @Eldenroot. I think I see what the problem is. I think the append-assign (.=) operator on [line 273 of activethreads.php](https://github.com/lairdshaw/MyBB-active-threads-plugin/blob/master/root/activethreads.php#L273) should be simply an assignment operator (=).

To test this, could you please change that line so that rather than starting with:
`		$conds .= `
it starts with:
`		$conds = `
and then let me know whether this fixes your user's problem?

**Comment by Eldenroot** [comment]
Thank you for your fast reply. The main problem is that I dont see the error,  I just get reports from other users on my board.

I have applied the changes above and we will see. I will let you know! Take care!

**Comment by lairdshaw** [comment]
Thanks!

**Comment by lairdshaw** [comment]
I know that the fix isn't yet confirmed, but the code needed to be corrected in any case. Feel free to reopen if the problem is still occurring.
