### ISSUE TITLE
Suggestion: Hide certain sub-forums from the active threads page

### ISSUE THREAD

**Issue by Amseog** [lairdshaw/MyBB-active-threads-plugin#21]
Dear laird, dear developers,
this is, in my opinion, one of the most amazing plugins for MyBB and it has become absolutely crucial to my board.
However, what would be really great in my opinion, would be the ability to filter which forums are included in the list of active threads. 

Background: On my board, there are several sub-forums that can be quite "spammy", with dozens of new threads created per day. It would be amazing to have to opportunity to hide these forums via their $fid from the active thread list.

Thank you very much for considering.

PS: Maybe this could also be done by myself via a small edit in the PHP file of your plugin. Any suggestions?

**Comment by lairdshaw** [comment]
I'm glad you get value out of this plugin, Amseog. Your suggestion was a good one: I've implemented it and released a new version of the plugin on the Extend site.

**Comment by Amseog** [comment]
How awesome you are, really! Kudos for being an amazing contributor to this free gem of a board system!

**Comment by Amseog** [comment]
Sorry, me again: I upgraded the plugin to version 1.3.0 -- amazing that the template changes are kept!
Subsequently, I found that in the plugin settings, I can now select forums (see attached image). In my example, "Hafenkiosk" is the board I do not want to show up on the active threads. However, this setting, in my case, doesn't change anything so far. I tried it with and without the containing main forum ("Promenade"), but in both cases, the active threads don't change.

Any ideas?

![aha](https://user-images.githubusercontent.com/5350651/152688626-d41e42c1-dec6-4354-83c7-88d4ec4c5f0c.PNG)

**Comment by Amseog** [comment]
Sorry for my previous long comment -- I now understood that the new setting means "Which forums to exclude" not "include". My bad. This works perfectly. Have a good day!

**Comment by lairdshaw** [comment]
No worries - I'm glad you worked it out. I otherwise had no explanation to offer!

There are a title and description for that setting which are pulled out of the language file `inc/languages/english/admin/activethreads.lang.php`, which presumably aren't showing up for you because your language is set to German. Here those strings are for reference:
```php
$l['act_excluded_forums_title'            ] = 'Excluded Forums';
$l['act_excluded_forums_desc'             ] = 'Select forums whose threads to exclude from the active listing';
```

**Comment by lairdshaw** [comment]
Oh, and I should add that selecting categories has no effect - only individual forums are counted - and nor does selecting an ordinary parent forum affect whether or not any child forums are counted. Perhaps that clarification should be added to the setting's description.
