### ISSUE TITLE
Poster avatar support 

### ISSUE THREAD

**Issue by Eldenroot** [lairdshaw/MyBB-active-threads-plugin#3]
- last post
- first post
- starter

**Comment by Eldenroot** [comment]
I mean to display user avatar :)

**Comment by lairdshaw** [comment]
OK, thank you, I see. Just to be clear: is this to mimic a feature found elsewhere in MyBB core code (or in an extension), or is it a totally original feature intended just for this plugin?

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/73592655-cffaf800-44fc-11ea-8d2a-3cd57516e735.png)

**Comment by lairdshaw** [comment]
OK, yes, I see. Is that part of core code, or is it provided by a custom skin? I ask because I can't find a setting to enable it in vanilla MyBB, and because it would be easier to leverage existing code if possible.

**Comment by Eldenroot** [comment]
It is not a core function... but it is not necessary to have that if it is too complicated

**Comment by lairdshaw** [comment]
I implemented it anyway - the display of each type of avatar (thread starter, earliest poster, latest poster) can be enabled in the plugin's settings.

**Comment by Eldenroot** [comment]
@lairdshaw - great! I am just testing, looks nice :) I will add more tickets when any idea will pop-up :)
