### ISSUE TITLE
Add templates for avatars

### ISSUE THREAD

**Issue by Eldenroot** [lairdshaw/MyBB-active-threads-plugin#6]
Make it easier to customize :)

**Comment by lairdshaw** [comment]
It's currently using the template 'member_profile_avatar' for avatars - so are you saying that you'd prefer that this plugin uses a unique template of its own for avatars that can be customised separately from that core template?

**Comment by Eldenroot** [comment]
Yeah, much better... :)

**Comment by Eldenroot** [comment]
It could contain same code as the default mybb stock template... but admisn could customize it as well easily :)

**Comment by lairdshaw** [comment]
OK, that makes sense.

**Comment by lairdshaw** [comment]
I've given you three. One for each type of avatar (thread starter; earliest poster; latest poster). You'll need to uninstall then reinstall for these changes to take effect as I haven't (yet) bumped the version number.
