### ISSUE TITLE
Variables for total posts in a thread/view?

### ISSUE THREAD

**Issue by Eldenroot** [lairdshaw/MyBB-active-threads-plugin#7]

**Comment by lairdshaw** [comment]
Are either of $row['num_posts'] or the formatted version, $num_posts_fmt, what you're looking for (see [line 458](https://github.com/lairdshaw/MyBB-active-threads-plugin/blob/61a6f4025b2e7d6bc0584bb16f7aea10e2d56fa7/root/activethreads.php#L458) of root/activethreads.php)?

**Comment by lairdshaw** [comment]
@Eldenroot, can this issue be closed or is your question still unanswered?

**Comment by Eldenroot** [comment]
You can close it
